name: flash-pro-dev
services:
  mongo:
    image: mongo:6.0
    container_name: dev_mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_dev:/data/db

  minio:
    image: minio/minio:latest
    container_name: dev_minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_dev:/data 

volumes:
  mongo_data_dev:
    driver: local
  minio_data_dev:
    driver: local