name: flash-pro-dev
services:
  mongo:
    image: mongo:6.0
    container_name: dev_mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_dev:/data/db

volumes:
  mongo_data_dev:
    driver: local