name: flash-pro
services:
  app:
    container_name: app
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ../../.env
    networks:
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: prod_minio
    restart: always
    ports:
      - ${MINIO_PORT}:9000
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_prod:/data
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
    driver: local
  minio_data:
    driver: local
