name: flash-pro
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nestjsdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
