name: backend-compose

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: create
        shell: cmd
        run: |
          echo ENVIRONMENT=${{ secrets.ENVIRONMENT }}> .env
          echo PORT=${{ secrets.PORT }}>> .env
          echo MONGO_URI=${{ secrets.MONGO_URI }}>> .env
          echo JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_ACCESS_SECRET_KEY }}>> .env
          echo JWT_ACCESS_EXPIRES_IN=${{ secrets.JWT_ACCESS_EXPIRES_IN }}>> .env
          echo JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }}>> .env
          echo JWT_REFRESH_EXPIRES_IN=${{ secrets.JWT_REFRESH_EXPIRES_IN }}>> .env
          echo ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}>> .env
          echo MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}>> .env
          echo MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}>> .env
          echo MINIO_BUCKET_NAME=${{ secrets.MINIO_BUCKET_NAME }}>> .env
          echo MINIO_PORT=${{ secrets.MINIO_PORT }}>> .env
          echo MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}>> .env
          echo MINIO_ACCESSKEY=${{ secrets.MINIO_ACCESSKEY }}>> .env
          echo MINIO_SECRETKEY=${{ secrets.MINIO_SECRETKEY }}>> .env

      - name: start container
        run: docker compose -f docker/prod/docker-compose.yml up --force-recreate --build --detach
