name: backend-compose

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: create environment
        run: |
          printf "ENVIRONMENT=${{ secrets.ENVIRONMENT }}\n" > .env
          printf "PORT=${{ secrets.PORT }}\n" >> .env
          printf "MONGO_URI=${{ secrets.MONGO_URI }}\n" >> .env
          printf "JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_ACCESS_SECRET_KEY }}\n" >> .env
          printf "JWT_ACCESS_EXPIRES_IN=${{ secrets.JWT_ACCESS_EXPIRES_IN }}\n" >> .env
          printf "JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }}\n" >> .env
          printf "JWT_REFRESH_EXPIRES_IN=${{ secrets.JWT_REFRESH_EXPIRES_IN }}\n" >> .env
          printf "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}\n" >> .env

      - name: start container
        run: docker compose -f docker/prod/docker-compose.yml up --force-recreate --build --detach
