name: backend-compose

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: docker compose -f docker/prod/docker-compose.yml up --force-recreate --build --detach
